os: osx
osx_image: xcode8
language: go
env:
  LDFLAGS:  -L/usr/local/opt/qt5/lib
  CPPFLAGS: -I/usr/local/opt/qt5/include
  PKG_CONFIG_PATH: /usr/local/opt/qt5/lib/pkgconfig
before_install:
  - brew update
  - brew install qt5
script: echo "So what next?"
